version: "3.8"

volumes:
  mariadb_data:
    driver: local

services:
  # Backend
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
    container_name: instagram-clone-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/instagram/:/home/instagram
    depends_on:
      - db

  # Frontend
  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
    container_name: instagram-clone-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/instagram/:/home/instagram
      - /home/instagram/node_modules
    depends_on:
      - backend

  # Banco principal
  db:
    image: mariadb:lts
    container_name: instagram-clone-db
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: instagram_db
      MARIADB_USER: instagram_user
      MARIADB_PASSWORD: instagram_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # Banco de teste para integração
  mariadb-test:
    image: mariadb:11
    container_name: mariadb-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagram_test
      MYSQL_USER: insta_user
      MYSQL_PASSWORD: insta_pass
    ports:
      - "3307:3306" # Porta local 3307 para evitar conflito
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "insta_user", "-pinsta_pass"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
